# Generated by Django 5.1.6 on 2025-02-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fretezon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frete',
            options={'managed': True, 'verbose_name': 'Frete', 'verbose_name_plural': 'fretes'},
        ),
        migrations.AlterModelTable(
            name='frete',
            table='frete',
        ),
    ]
